[package]
name = "rtdlib"
version = "0.3.0"
authors = ["fewensa <fewensa@protonmail.com>"]
description = "TDLib for rust"
homepage = "https://github.com/fewensa/rtdlib"
repository = "https://github.com/fewensa/rtdlib"
license = "MIT"
keywords = ["tdlib", "telegram", "bindings"]
categories = ["api-bindings"]
include = [
  "Cargo.toml",
  "**/*.rs",
  "**/*.tpl.txt",
  "**/*.tpl.toml",
  "README.md",
  "LICENSE"
]
readme = "README.md"
edition = "2018"

build = "build/build.rs"

[dependencies]
libc = "0.2"

serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
typetag = "0.1.2"

strum = "0.15.0"
strum_macros = "0.15.0"

text-reader = "0.2.1"
rstring-builder = "0.1.4"

[build-dependencies]
